In [4]:
#Importing Libraries
import pandas as pd
import selenium
from selenium import webdriver
import time
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException, ElementNotInteractableException
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
import os
import urllib
import requests

# 1 

Scrape the details of most viewed videos on YouTube from Wikipedia:
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/
You need to find following details:
A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [5]:
#1
#importing webdriver
driver=webdriver.Chrome("chromedriver.exe")
driver.maximize_window()  #maximizing window
time.sleep(3)
url="https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos"   #"url"
driver.get(url) #loading url
time.sleep(2)

#creating empty Boxex
rank=[]
videon=[]
uploader=[]
views=[]
uploadd=[]

for i in range(1,31):
    #Rank
    dt=driver.find_elements_by_xpath("//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{}]/td[1]".format(i))
    for d in dt:
        rank.append(d.text)
    #video name
    vi=driver.find_elements_by_xpath("//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{}]/td[2]".format(i))
    for c in vi:
        videon.append(c.text)
        videon = [x.split("[")[0] for x in videon] #cleaning data
        
    #Uploader
    l=driver.find_elements_by_xpath("//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{}]/td[3]".format(i))
    for g in l:
        uploader.append(g.text)
    #Views
    vs=driver.find_elements_by_xpath("//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{}]/td[4]".format(i))
    for h in vs:
        views.append(h.text)
   #Upload date
    up=driver.find_elements_by_xpath("//*[@id='mw-content-text']/div[1]/table[3]/tbody/tr[{}]/td[5]".format(i))
    for c in up:
        uploadd.append(c.text)

time.sleep(2)
#creating dataframe
ans1=pd.DataFrame({})
ans1["Rank"]=rank
ans1["Video Name"]=videon
ans1["Uploader"]=uploader
ans1["Views (billions)"]=views 
ans1["Upload Date"]=uploadd
ans1.set_index("Rank", inplace=True)
ans1

,Video Name,Uploader,Views (billions),Upload Date
Rank,,,,
1.,"""Baby Shark Dance""",Pinkfong Kids' Songs & Stories,8.74,"June 17, 2016"
2.,"""Despacito""",Luis Fonsi,7.39,"January 12, 2017"
3.,"""Johny Johny Yes Papa""",LooLoo Kids,5.43,"October 8, 2016"
4.,"""Shape of You""",Ed Sheeran,5.34,"January 30, 2017"
5.,"""See You Again""",Wiz Khalifa,5.13,"April 6, 2015"
6.,"""Masha and the Bear – Recipe for Disaster""",Get Movies,4.44,"January 31, 2012"
7.,"""Uptown Funk""",Mark Ronson,4.20,"November 19, 2014"
8.,"""Learning Colors – Colorful Eggs on a Farm""",Miroshka TV,4.14,"February 27, 2018"
9.,"""Bath Song""",Cocomelon – Nursery Rhymes,4.12,"May 2, 2018"
10.,"""Gangnam Style""",Psy,4.08,"July 15, 2012"
11.,"""Phonics Song with Two Words""",ChuChu TV,3.91,"March 6, 2014"
12.,"""Sugar""",Maroon 5,3.48,"January 14, 2015"
13.,"""Sorry""",Justin Bieber,3.44,"October 22, 2015"
14.,"""Dame Tu Cosita""",El Chombo,3.38,"April 5, 2018"
15.,"""Roar""",Katy Perry,3.36,"September 5, 2013"
16.,"""Counting Stars""",OneRepublic,3.31,"May 31, 2013"
17.,"""Thinking Out Loud""",Ed Sheeran,3.27,"October 7, 2014"
18.,"""Dark Horse""",Katy Perry,3.08,"February 20, 2014"
19.,"""Faded""",Alan Walker,3.08,"December 3, 2015"
20.,"""Wheels on the Bus""",Cocomelon – Nursery Rhymes,3.07,"May 24, 2018"
21.,"""Shake It Off""",Taylor Swift,3.06,"August 18, 2014"
22.,"""Lean On""",Major Lazer,3.05,"March 22, 2015"
23.,"""Girls Like You""",Maroon 5,3.04,"May 31, 2018"
24.,"""Bailando""",Enrique Iglesias,3.04,"April 11, 2014"
25.,"""Let Her Go""",Passenger,3.00,"July 25, 2012"
26.,"""Mi Gente""",J Balvin,2.93,"June 29, 2017"
27.,"""Perfect""",Ed Sheeran,2.86,"November 9, 2017"
28.,"""Hello""",Adele,2.84,"October 22, 2015"
29.,"""Waka Waka (This Time for Africa)""",Shakira,2.84,"June 4, 2010"
30.,"""Axel F""",Crazy Frog,2.83,"June 16, 2009"

# Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Match title (I.e. 1st ODI)
B) Series
C) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [31]:
#2
#importing webdriver
driver=webdriver.Chrome("chromedriver.exe")
driver.maximize_window() #maximizing window
time.sleep(3)
url="https://www.bcci.tv/"   #"url"
driver.get(url) #loading url
time.sleep(3)

#clicking on fixture button
fixtures=driver.find_element_by_xpath("//div[@class='navigation__drop-down drop-down drop-down--reveal-on-hover']/div/ul/li/a")
try:
    fixtures.click()

except ElementNotInteractableException:
    driver.get(fixtures.get_attribute('href'))
time.sleep(3)

#creating boxex
mt=[]
series=[]
place=[]
date=[]
ti=[]
month=[]

#Match Title 
d=driver.find_elements_by_xpath("//strong[@class='fixture__name fixture__name--with-margin']")
for i in d:
    mt.append(i.text)

#Series    
s=driver.find_elements_by_xpath("//span[@class='u-unskewed-text fixture__tournament-label u-truncated']")
for i in s:
    series.append(i.text)

#Place
p=driver.find_elements_by_xpath("//p[@class='fixture__additional-info']/span")
for i in p:
    place.append(i.text)
    
#Date    
z=driver.find_elements_by_xpath("//span[@class='fixture__date']")
for i in z:
    date.append(i.text)
    
#Month
h=driver.find_elements_by_xpath("//span[@class='fixture__month']")
for i in h:
    month.append(i.text)
    
#time
v=driver.find_elements_by_xpath("//span[@class='fixture__time']")
for i in v:
    ti.append(i.text)
    
time.sleep(2)
#creating dataframe
ans2=pd.DataFrame({})
ans2["Match Title"]=mt
ans2["Series"]=series
ans2["Place"]=place
ans2["Date"]=date 
ans2["Month"]=month
ans2["Date"]=ans2["Date"]+" " + ans2["Month"]   #adding date and month in one column
ans2.drop("Month",axis=1,inplace=True)
ans2["Time"]=ti
ans2

,Match Title,Series,Place,Date,Time
0,Final,ICC WORLD TEST CHAMPIONSHIP,"The Ageas Bowl, Southampton",18 JUNE,15:00 IST
1,1st Test,ENGLAND V INDIA 2021,"Trent Bridge, Nottingham",04 AUGUST,15:30 IST
2,2nd Test,ENGLAND V INDIA 2021,"Lord's, London",12 AUGUST,15:30 IST
3,3rd Test,ENGLAND V INDIA 2021,"Headingley, Leeds",25 AUGUST,15:30 IST
4,4th Test,ENGLAND V INDIA 2021,"The Oval, London",02 SEPTEMBER,15:30 IST
5,5th Test,ENGLAND V INDIA 2021,"Old Trafford, Manchester",10 SEPTEMBER,15:30 IST

# 3
Scrape the details of selenium exception from guru99.com.
Url = https://www.guru99.com/
You need to find following details:
A) Name
B) Description
Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [7]:
#2
#importing webdriver
driver=webdriver.Chrome("chromedriver.exe")
driver.maximize_window() #maximizing windows
time.sleep(3)
url="https://www.guru99.com/"   #"url"
driver.get(url) #loading url
time.sleep(3)

#Selecting selenium in texting column
s=driver.find_element_by_xpath("//*[@id='java_technologies']/li[3]/a")
s.click()
time.sleep(3)


# selecting "Selenium Exception Handling (Common Exceptions List)"
driver.find_element_by_xpath("/html/body/div[2]/section[3]/div/div[1]/main/div/div/div/div/div/div/div[2]/table[5]/tbody/tr[34]/td[1]/a/strong").click()

#creating empty boxes
en=[]
des=[]


for i in range(2,43):
    #Exception name
    dt=driver.find_elements_by_xpath("//*[@id='g-mainbar']/div[1]/div/div/div/div/div/div[2]/table/tbody/tr[{}]/td[1]".format(i))
    for d in dt:
        en.append(d.text)
      
    #Description
    gt=driver.find_elements_by_xpath("//*[@id='g-mainbar']/div[1]/div/div/div/div/div/div[2]/table/tbody/tr[{}]/td[2]".format(i))
    for c in gt:
        des.append(c.text)

time.sleep(2)
#creating dataframe
ans3=pd.DataFrame({})
ans3["Exception Name"]=en
ans3["Description"]=des  
ans3

,Exception Name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can't be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n't sen...

# 4
Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details:
A) Rank
B) State
C) GSDP at current price (19-20)
D) GSDP at current price (18-19)
E) Share(18-19)
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code.

In [6]:
#4
#importing webdriver
driver=webdriver.Chrome("chromedriver.exe")
driver.maximize_window()
time.sleep(3)
url="http://statisticstimes.com/"   #"url"
driver.get(url)  #loading url
time.sleep(2)

#Selecting india in economy dropdown
gdp=driver.find_element_by_xpath("//*[@id='top']/div[2]/div[2]/div/a[3]")

try:
    gdp.click()

except ElementNotInteractableException:
    driver.get(gdp.get_attribute('href'))
time.sleep(3)

#selecting state gdp
driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[2]/ul/li[1]/a").click()

#creating empty boxes
rank=[]
state=[]
gs19=[]
gs18=[]
share=[]
gd=[]

#extraxting data
for i in range(1,34):
    #Rank
    dt=driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr[{}]/td[1]".format(i))
    for d in dt:
        rank.append(d.text)
    #State
    vi=driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr[{}]/td[2]".format(i))
    for c in vi:
        state.append(c.text)
    #GSDP (Cr INR at Current prices)19-20
    l=driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr[{}]/td[3]".format(i))
    for g in l:
        gs19.append(g.text)
    #GSDP (Cr INR at Current prices)18-19
    vs=driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr[{}]/td[4]".format(i))
    for h in vs:
        gs18.append(h.text)
   #share
    up=driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr[{}]/td[5]".format(i))
    for c in up:
        share.append(c.text)
    #GDP($Billion)    
    dt=driver.find_elements_by_xpath("//*[@id='table_id']/tbody/tr[{}]/td[5]".format(i))
    for z in dt:
        gd.append(z.text)

time.sleep(2)
#creating dataframe
ans4=pd.DataFrame({})
ans4["Rank"]=rank
ans4["State"]=state
ans4["GSDP (Cr INR at Current prices)19-20"]=gs19
ans4["GSDP (Cr INR at Current prices)18-19"]=gs18 
ans4["Share"]=share
ans4["GDP($Billion)"]=gd
ans4.set_index("Rank", inplace=True) #setting rank column as index
ans4

,State,GSDP (Cr INR at Current prices)19-20,GSDP (Cr INR at Current prices)18-19,Share,GDP($Billion)
Rank,,,,,
1,Maharashtra,-,"2,632,792",13.94%,13.94%
2,Tamil Nadu,"1,845,853","1,630,208",8.63%,8.63%
3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,8.39%
4,Gujarat,-,"1,502,899",7.96%,7.96%
5,Karnataka,"1,631,977","1,493,127",7.91%,7.91%
6,West Bengal,"1,253,832","1,089,898",5.77%,5.77%
7,Rajasthan,"1,020,989","942,586",4.99%,4.99%
8,Andhra Pradesh,"972,782","862,957",4.57%,4.57%
9,Telangana,"969,604","861,031",4.56%,4.56%
10,Madhya Pradesh,"906,672","809,592",4.29%,4.29%
11,Kerala,-,"781,653",4.14%,4.14%
12,Delhi,"856,112","774,870",4.10%,4.10%
13,Haryana,"831,610","734,163",3.89%,3.89%
14,Bihar,"611,804","530,363",2.81%,2.81%
15,Punjab,"574,760","526,376",2.79%,2.79%
16,Odisha,"521,275","487,805",2.58%,2.58%
17,Assam,-,"315,881",1.67%,1.67%
18,Chhattisgarh,"329,180","304,063",1.61%,1.61%
19,Jharkhand,"328,598","297,204",1.57%,1.57%
20,Uttarakhand,-,"245,895",1.30%,1.30%
21,Jammu & Kashmir,-,"155,956",0.83%,0.83%
22,Himachal Pradesh,"165,472","153,845",0.81%,0.81%
23,Goa,"80,449","73,170",0.39%,0.39%
24,Tripura,"55,984","49,845",0.26%,0.26%
25,Chandigarh,-,"42,114",0.22%,0.22%
26,Puducherry,"38,253","34,433",0.18%,0.18%
27,Meghalaya,"36,572","33,481",0.18%,0.18%
28,Sikkim,"32,496","28,723",0.15%,0.15%
29,Manipur,"31,790","27,870",0.15%,0.15%
30,Nagaland,-,"27,283",0.14%,0.14%
31,Arunachal Pradesh,-,"24,603",0.13%,0.13%
32,Mizoram,"26,503","22,287",0.12%,0.12%
33,Andaman & Nicobar Islands,-,-,-,-

# 5
Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used

In [26]:
#5
#importing webdriver
driver=webdriver.Chrome("chromedriver.exe")
driver.maximize_window()  #maximizing windows
time.sleep(3)
url="https://github.com/"   #"url"
driver.get(url)  #loading url
time.sleep(3)

#Selecting Trending from explore
tred=driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul[2]/li[3]/a")

try:
    tred.click()

except ElementNotInteractableException:
    driver.get(tred.get_attribute('href'))
time.sleep(3)


time.sleep(3)

# Getting urls for data extraction
urls=[]
url=driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a")
for i in url:
    urls.append(i.get_attribute("href"))

#creating boxes    
rt=[]
rd=[]
cc=[]
lu=[]


#extracting data
for i in urls:
    driver.get(i)
    time.sleep(3)
    
#respositery title
    try:
        c=driver.find_element_by_xpath("//*[@id='js-repo-pjax-container']/div[1]/div[1]/div")
        rt.append(c.text)
    except NoSuchElementException:
        rt.append("--")
#repositery description
    try:
        z=driver.find_element_by_xpath("//p[@class='f4 mt-3']")
        rd.append(z.text)
    except NoSuchElementException:
        rd.append("--")
#Contributor count
    try:
        d=driver.find_element_by_xpath('//*[@id="repo-content-pjax-container"]/div/div[2]/div[2]/div/div[5]/div/h2/a/span')
        cc.append(d.text)
    except NoSuchElementException:
        cc.append("--")
#language used
    try:
        c=driver.find_element_by_xpath("//*[@id='repo-content-pjax-container']/div/div[2]/div[2]/div/div[6]/div/ul")
        lu.append(c.text)
    except NoSuchElementException:
        lu.append("--")
    
time.sleep(2)
#creating dataframe
ans5=pd.DataFrame({})
ans5["Repositery Title"]=rt
ans5["Repositery Description"]=rd
ans5["Contributor count"]=cc
ans5["Languages"]=lu

ans5

,Repositery Title,Repositery Description,Contributor count,Languages
0,facebookresearch\n/\nAugLy,"A data augmentations library for audio, image,...",5,Python\n100.0%
1,programthink\n/\nzhao,【编程随想】整理的《太子党关系网络》，专门揭露赵国的权贵,--,--
2,megaease\n/\neasegress,A Cloud Native traffic orchestration system,--,--
3,keras-team\n/\nkeras,Deep Learning for humans,883,Python\n97.6%\nStarlark\n2.3%\nShell\n0.1%
4,ibraheemdev\n/\nmodern-unix,A collection of modern/faster/saner alternativ...,--,--
5,tailwindlabs\n/\ntailwindcss,A utility-first CSS framework for rapid UI dev...,177,JavaScript\n79.1%\nCSS\n16.1%\nHTML\n4.7%\nOth...
6,n8n-io\n/\nn8n,Free and open fair-code licensed node based Wo...,173,TypeScript\n94.9%\nVue\n4.9%\nSCSS\n0.1%\nJava...
7,harvester\n/\nharvester,Open source hyperconverged infrastructure (HCI...,--,--
8,organicmaps\n/\norganicmaps,"🍃 Organic Maps is a better fork of MAPS.ME, an...",--,--
9,longhorn\n/\nlonghorn,Cloud-Native distributed block storage built o...,--,--
10,rancher\n/\nrancher,Complete container management platform,--,--
11,rustdesk\n/\nrustdesk,Yet another remote desktop software,--,
12,kwai\n/\nDouZero,[ICML 2021] DouZero: Mastering DouDizhu with S...,2,Python\n98.8%\nShell\n1.2%
13,cariboulabs\n/\ncariboulite,CaribouLite turns any 40-pin Raspberry-Pi into...,3,C\n72.9%\nAGS Script\n23.6%\nVerilog\n2.6%\nOt...
14,willmcgugan\n/\ntextual,A Text User Interface with Rich as the renderer,4,Python\n100.0%
15,prisma\n/\nprisma,Next-generation ORM for Node.js & TypeScript |...,--,--
16,apache\n/\nincubator-shenyu,ShenYu is High-Performance Java API Gateway.,173,Java\n99.4%\nOther\n0.6%
17,academic\n/\nawesome-datascience,📝 An awesome Data Science repository to learn ...,--,
18,vxunderground\n/\nMalwareSourceCode,Collection of malware source code for a variet...,--,--
19,bats3c\n/\nDarkLoadLibrary,LoadLibrary for offensive operations,--,--
20,EssayKillerBrain\n/\nEssayKiller_V2,基于开源GPT2.0的初代创作型人工智能 | 可扩展、可进化,--,--
21,gohugoio\n/\nhugo,The world’s fastest framework for building web...,--,
22,thanos-io\n/\nthanos,Highly available Prometheus setup with long te...,356,Go\n80.8%\nTypeScript\n10.4%\nJsonnet\n3.4%\nJ...
23,benthecoder\n/\nyt-channels-DS-AI-ML-CS,A comprehensive list of YouTube Channels for D...,--,--
24,AkashSingh3031\n/\nThe-Complete-FAANG-Preparation,This repository contains all the DSA (Data-Str...,--,--

# 6
Scrape the details of top 100 songs on billboard.com.
Url = https://www.billboard.com/
You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [13]:
#importing webdriver
driver=webdriver.Chrome("chromedriver.exe")  #maximizing window
driver.maximize_window()
time.sleep(3)
url="https://www.billboard.com/"   #"url"
driver.get(url)  #loading url
time.sleep(5)

#getting hot 100 songs from dropdown
chart=driver.find_element_by_xpath("//*[@id='menu-charts-desktop']/span/span/span[1]/ul/li[1]/a")

try:
    chart.click()

except ElementNotInteractableException:
    driver.get(chart.get_attribute('href'))
time.sleep(3)


#creating boxes
sname=[]
aname=[]
lr=[]
pr=[]
wb=[]


#Song
c=driver.find_elements_by_xpath("//span[@class='chart-element__information__song text--truncate color--primary']")
for i in c:
    sname.append(i.text)

#Artist
z=driver.find_elements_by_xpath("//span[@class='chart-element__information__artist text--truncate color--secondary']")
for v in z: 
    aname.append(v.text)

#Last rank
d=driver.find_elements_by_xpath('//div[@class="chart-element__meta text--center color--secondary text--last"]')
for h in d:    
    lr.append(h.text)

#Peak Rank
c=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--peak']")
for t in c:
    pr.append(t.text)

#WKS on chart
g=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--week']")
for b in g:
    wb.append(b.text)

time.sleep(2)
#creating dataframe
ans6=pd.DataFrame({})
ans6["Song"]=sname
ans6["Artist"]=aname
ans6["Last Week Rank"]=lr
ans6["Peak rank"]=pr
ans6["Weeks on board"]=wb
ans6

,Song,Artist,Last Week Rank,Peak rank,Weeks on board
0,Butter,BTS,1,1,2
1,Good 4 U,Olivia Rodrigo,2,1,3
2,Levitating,Dua Lipa Featuring DaBaby,4,2,35
3,Leave The Door Open,Silk Sonic (Bruno Mars & Anderson .Paak),5,1,13
4,Save Your Tears,The Weeknd & Ariana Grande,7,1,25
...,...,...,...,...,...
95,All I Know So Far,P!nk,87,74,3
96,Hold On,Justin Bieber,86,20,13
97,Wasted On You,Morgan Wallen,98,9,19
98,Outside,MO3 X OG Bobby Billions,-,99,1
99,Botella Tras Botella,Gera MX + Christian Nodal,-,60,4

# 7
Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/
You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location
Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and 
click on search. All this should be done through code

In [25]:
#importing webdriver
driver=webdriver.Chrome("chromedriver.exe")
driver.maximize_window() #maximizing windows
time.sleep(3)
url="https://www.naukri.com/"   #"url"
driver.get(url) #loading url
time.sleep(3)


#clicking on recruiters
driver.find_element_by_xpath("//*[@id='root']/div[1]/div/ul[1]/li[2]/a").click()
time.sleep(5)

#shifting tab since the recruiters opened in new tab
driver.switch_to.window(driver.window_handles[-4])  #we have used value -4 because there are 3 add popups
time.sleep(2)

#searching search bar
searchb=driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/div/div[1]/div[1]/div[2]/input")

#putting key words
keyword="Data Science"
searchb.send_keys(keyword)

#cliacking on search button
driver.find_element_by_xpath("//*[@id='qsbFormBtn']").click()
time.sleep(3)


#ccreating expty boxes
name=[]
des=[]
com=[]
sh=[]
lo=[]



#extracting data
#name
c=driver.find_elements_by_xpath("//span[@class='fl ellipsis']")
for i in c:
    name.append(i.text)

#Designation
z=driver.find_elements_by_xpath("//span[@class='ellipsis clr']")
for v in z: 
    des.append(v.text)

#Company
d=driver.find_elements_by_xpath('//a[@class="ellipsis"]')
for h in d:    
    com.append(h.text)
f=com[1::2]

#Skill they hire
c=driver.find_elements_by_xpath("//div[@class='hireSec highlightable']")
for t in c:
    sh.append(t.text)

#Location
urls=[]
location=driver.find_elements_by_xpath("//a[@class='ellipsis']")
for i in location:
    urls.append(i.get_attribute("href"))
urls=urls[0::2]

for i in urls:
    driver.get(i)
    time.sleep(3)
    t=driver.find_element_by_xpath("/html/body/div[2]/div[1]/div[1]/div[2]/div[5]/a")
    try:
        lo.append(t.text)
    except NoSuchElementException:
        lo.append("--")



time.sleep(2)
#creating dataframe
ans7=pd.DataFrame({})
ans7["Name"]=name
ans7["Designation"]=des
ans7["Company"]=f
ans7["Skill they hire"]=sh
ans7["Location"]=lo
ans7

,Name,Designation,Company,Skill they hire,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Indore
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
10,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
11,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
12,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Mumbai
13,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
14,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
15,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
16,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
17,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
18,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Delhi
19,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
20,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Pune
21,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Pune
22,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Pune
23,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
24,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
25,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
26,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",Others
27,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Delhi
28,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Bengaluru / Bangalore
29,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Bengaluru / Bangalore
30,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Mysoru / Mysore
31,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,"Data Science, Machine Learning, Big Data Analy...",Hyderabad / Secunderabad
32,Radha Manivasagam,HR Executive,Techcovery,"Python, Artificial Intelligence, Machine Learn...",Bengaluru / Bangalore
33,Prateek Kumar,Head,Trisect,"Java, Python, Angularjs, Software Testing, Mac...",Noida
34,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",New Delhi
35,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Chennai
36,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Aligarh
37,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Salt Lake City
38,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Pune
39,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Bengaluru / Bangalore
40,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Mumbai
41,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Indore
42,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",Bengaluru / Bangalore
43,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",MYSORE
44,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Hyderabad / Secunderabad
45,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Bengaluru / Bangalore
46,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Mumbai
47,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage...",
48,Shailja Mishra,HR Manager,Certybox Pvt.Ltd.,"consulting, Education Counseling, Educational ...",Noida
49,Sunny Sharma,Managing Director - HR,Western Service Providers,"Software Professionals, Engineering, Technical...",Mumbai

# 8
Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [37]:
#importing webdriver
driver=webdriver.Chrome("chromedriver.exe")
driver.maximize_window() #maximizing windows
time.sleep(3)
url="https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare"   #"url"
driver.get(url) #loading url
time.sleep(3)

#creating boxes
name=[]
aut=[]
vs=[]
pu=[]
ge=[]


#extracting data
for i in range(0,101):
#Book Name
    c=driver.find_elements_by_xpath("/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{}]/td[2]".format(i))
    for q in c:
        name.append(q.text)

#AUthor
    z=driver.find_elements_by_xpath("/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{}]/td[3]".format(i))
    for v in z:
        aut.append(v.text)

#Volumes sold
    d=driver.find_elements_by_xpath("/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{}]/td[4]".format(i))    
    for h in d:
        vs.append(h.text)

#Publisher
    c=driver.find_elements_by_xpath("/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{}]/td[5]".format(i))
    for t in c:
        pu.append(t.text)

#Genre
    g=driver.find_elements_by_xpath("/html/body/div/div[2]/div[2]/div/div[2]/div/table/tbody/tr[{}]/td[6]".format(i))
    for b in g:
        ge.append(b.text)
    
time.sleep(2)
#creating dataframe
ans8=pd.DataFrame({})
ans8["Book Name"]=name
ans8["Author"]=aut
ans8["Volumes sold"]=vs
ans8["Publisher"]=pu
ans8["Genre"]=ge
ans8

,Book Name,Author,Volumes sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# 9
Scrape the details most watched tv series of all time from imdb.com.
 Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [21]:
#importing webdriver
driver=webdriver.Chrome("chromedriver.exe")
driver.maximize_window() #maximizing windows
time.sleep(3)
url="https://www.imdb.com/list/ls095964455/"   #"url"
driver.get(url) #loading url
time.sleep(3)

#creating boxes
name=[]
year=[]
ge=[]
rt=[]
rating=[]
votes=[]


#extracting data
#name
c=driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a")
for i in c:
    name.append(i.text)

#Year span
z=driver.find_elements_by_xpath("//span[@class='lister-item-year text-muted unbold']")
for i in z:
    year.append(i.text)

#Genre
v=driver.find_elements_by_xpath("//span[@class='genre']")
for i in v:
    ge.append(i.text)

#Run Time
y=driver.find_elements_by_xpath("//span[@class='runtime']")
for i in y:
    rt.append(i.text)

#Rating
t=driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']")
for i in t:
    rating.append(i.text)

#votes
r=driver.find_elements_by_xpath("//span[@name='nv']")
for i in r:
    votes.append(i.text)

time.sleep(2)
#creating dataframe
ans9=pd.DataFrame({})
ans9["Name"]=name
ans9["Year span"]=year
ans9["Genre"]=ge
ans9["Run time"]=rt
ans9["Rating"]=rating
ans9["Votes"]=votes
ans9

,Name,Year span,Genre,Run time,Rating,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.3,"1,823,384"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"863,908"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"874,524"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.6,"262,699"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"224,042"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42 min,7.5,"44,578"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"55,072"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8,"167,742"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"34,888"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"191,426"

# 10
Details of Datasets from UCI machine learning repositories.
 Url = https://archive.ics.uci.edu/
 You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year
Note: - from the home page you have to go to the Show All Dataset page through code

In [33]:
#importing webdriver
driver=webdriver.Chrome("chromedriver.exe")
driver.maximize_window()   #maximizing windows
time.sleep(3)
url="https://archive.ics.uci.edu/ml/index.php"   #"url"
driver.get(url)  #loading url
time.sleep(3)

#clicking on view all data sets
driver.find_element_by_xpath("/html/body/table[1]/tbody/tr/td[2]/span[2]").click()


#creating empty boxes
time.sleep(3)
name=[]
dtype=[]
task=[]
at=[]
noi=[]
noa=[]
year=[]


#extracting dataset
for i in range(2,590):
    
#Dataset name
    c=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{}]/td[1]/table/tbody/tr/td[2]/p".format(i))
    for a in c:
        name.append(a.text)

# Data Type
    z=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{}]/td[2]/p".format(i))
    for c in z:
        dtype.append(c.text)

#Task
    v=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{}]/td[3]".format(i))
    for t in v:
        task.append(t.text)

#Attribute type
    y=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{}]/td[4]".format(i))
    for u in y:
        at.append(u.text)

#NO. of instances
    t=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{}]/td[5]".format(i))
    for r in t:
        noi.append(r.text)

#No. of attribute
    r=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{}]/td[6]".format(i))
    for w in r:
        noa.append(w.text)

#Year
    w=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr[{}]/td[7]".format(i))
    for y in w:
        year.append(y.text)


    
time.sleep(2)
#creating dataframe
ans10=pd.DataFrame({})
ans10["Dataset Name"]=name
ans10["Data Type"]=dtype
ans10["Task"]=task
ans10["Attribute Type"]=at
ans10["No. of instances"]=noi
ans10["No. of Attributes"]=noa
ans10["Year"]=year
ans10

,Dataset Name,Data Type,Task,Attribute Type,No. of instances,No. of Attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
583,in-vehicle coupon recommendation,Multivariate,Classification,,12684,23,2020
584,Gait Classification,Multivariate,Classification,Real,48,321,2020
585,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
586,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
587,Synchronous Machine Data Set,Multivariate,Regression,Real,557,5,2021